/**
 * Quiz Data for MuslimGuard
 * Islamic quiz questions organized by category and difficulty
 *
 * To add questions: simply add new objects to the `questions` array
 * of any category. Each question needs:
 * - question: the question text
 * - choices: array of 4 possible answers
 * - correctIndex: index (0-3) of the correct answer
 * - difficulty: 'easy' | 'normal' | 'hard'
 * - explanation: (optional) short explanation shown after answering
 */

export type QuizDifficulty = 'easy' | 'normal' | 'hard';

export interface QuizQuestion {
  question: string;
  choices: string[];
  correctIndex: number;
  explanation?: string;
  difficulty: QuizDifficulty;
}

export interface QuizCategory {
  id: string;
  label: string;
  icon: string; // MaterialCommunityIcons name
  image: any; // require() image source
  color: string;
  colorLight: string;
  gradient: [string, string];
  questions: QuizQuestion[];
}

export const DIFFICULTY_CONFIG: Record<QuizDifficulty, { label: string; icon: string; color: string; colorLight: string; gradient: [string, string]; timerSeconds: number | null }> = {
  easy: { label: 'Facile', icon: 'star-outline', color: '#4CAF50', colorLight: '#E8F5E9', gradient: ['#4CAF50', '#81C784'], timerSeconds: null },
  normal: { label: 'Normal', icon: 'star-half-full', color: '#FF9800', colorLight: '#FFF3E0', gradient: ['#FF9800', '#FFB74D'], timerSeconds: null },
  hard: { label: 'Difficile', icon: 'star', color: '#F44336', colorLight: '#FFEBEE', gradient: ['#F44336', '#E57373'], timerSeconds: 15 },
};

export const QUIZ_CATEGORIES: QuizCategory[] = [
  {
    id: 'prophets',
    label: 'Les Prophètes',
    icon: 'family-tree',
    image: require('@/assets/quiz/prophetes.png'),
    color: '#1565C0',
    colorLight: '#E3F2FD',
    gradient: ['#1565C0', '#42A5F5'],
    questions: [
      // === EASY ===
      {
        question: 'Qui est le premier prophète de l\'Islam ?',
        choices: ['Ibrahim (عَلَيْهِ ٱلسَّلَامُ)', 'Adam (عَلَيْهِ ٱلسَّلَامُ)', 'Nouh (عَلَيْهِ ٱلسَّلَامُ)', 'Moussa (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 1,
        explanation: 'Adam (عَلَيْهِ ٱلسَّلَامُ) est le premier homme et le premier prophète créé par Allah.',
        difficulty: 'easy',
      },
      {
        question: 'Quel prophète a construit l\'Arche ?',
        choices: ['Souleyman (عَلَيْهِ ٱلسَّلَامُ)', 'Nouh (عَلَيْهِ ٱلسَّلَامُ)', 'Daoud (عَلَيْهِ ٱلسَّلَامُ)', 'Ismaïl (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 1,
        explanation: 'Allah a ordonné à Nouh (عَلَيْهِ ٱلسَّلَامُ) de construire l\'Arche pour sauver les croyants du déluge.',
        difficulty: 'easy',
      },
      {
        question: 'Quel prophète a été avalé par un poisson ?',
        choices: ['Younes (عَلَيْهِ ٱلسَّلَامُ)', 'Moussa (عَلَيْهِ ٱلسَّلَامُ)', 'Issa (عَلَيْهِ ٱلسَّلَامُ)', 'Idris (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 0,
        explanation: 'Younes (عَلَيْهِ ٱلسَّلَامُ) a été avalé par un gros poisson après avoir quitté son peuple. Il a invoqué Allah dans le ventre du poisson.',
        difficulty: 'easy',
      },
      {
        question: 'Qui est le dernier prophète ?',
        choices: ['Issa (عَلَيْهِ ٱلسَّلَامُ)', 'Ibrahim (عَلَيْهِ ٱلسَّلَامُ)', 'Mohammed (ﷺ)', 'Moussa (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 2,
        explanation: 'Mohammed (ﷺ) est le sceau des prophètes, le dernier messager envoyé par Allah à l\'humanité.',
        difficulty: 'easy',
      },
      {
        question: 'Quel Prophète est resté très patient malgré une longue maladie et la perte de ses biens ?',
        choices: ['Yusuf', 'Ayoub (Job)', 'Yunus', 'Moussa'],
        correctIndex: 1,
        explanation: 'Ayoub est l\'exemple même de la patience (Sabr) face aux épreuves de la vie.',
        difficulty: 'easy',
      },
      {
        question: 'Quel Prophète est le père de Ismaël et de Ishaq ?',
        choices: ['Adam', 'Nuh', 'Ibrahim (Abraham)', 'Lut'],
        correctIndex: 2,
        explanation: 'Ibrahim est surnommé le "Père des Prophètes" car beaucoup de messagers sont issus de sa descendance.',
        difficulty: 'easy',
      },
      {
        question: 'Quel Prophète a été envoyé au peuple de Madyan pour leur dire d\'être honnêtes dans le commerce ?',
        choices: ['Salih', 'Shu\'ayb', 'Hud', 'Lut'],
        correctIndex: 1,
        explanation: 'Shu\'ayb demandait à son peuple de ne pas tricher sur le poids et la mesure lors des ventes.',
        difficulty: 'easy',
      },
      {
        question: 'Comment s\'appelait le frère du Prophète Moussa qui l\'a aidé face à Pharaon ?',
        choices: ['Haroun (Aaron)', 'Yusuf', 'Ishaq', 'Yahiya'],
        correctIndex: 0,
        explanation: 'Haroun était le porte-parole et le soutien de son frère Moussa dans sa mission.',
        difficulty: 'easy',
      },
      {
        question: 'Quel Prophète a été envoyé au peuple des \'Ad ?',
        choices: ['Hud', 'Salih', 'Nuh', 'Shu\'ayb'],
        correctIndex: 0,
        explanation: 'Le Prophète Hud a appelé le peuple des \'Ad à ne plus adorer les idoles et à remercier Allah pour leurs richesses.',
        difficulty: 'easy',
      },
      {
        question: 'Quel Prophète est monté au ciel lors du voyage nocturne (Al-Isra wal-Miraj) ?',
        choices: ['Muhammad (ﷺ)', 'Moussa', 'Issa', 'Ibrahim'],
        correctIndex: 0,
        explanation: 'Le Prophète Muhammad (ﷺ) a voyagé de La Mecque à Jérusalem puis à travers les sept cieux en une seule nuit.',
        difficulty: 'easy',
      },
      {
        question: 'Quel Prophète était le fils de Zakariya et le cousin de \'Issa ?',
        choices: ['Yahya (Jean)', 'Yunus', 'Idris', 'Dawoud'],
        correctIndex: 0,
        explanation: 'Yahya était un Prophète très pieux et sage dès son plus jeune âge.',
        difficulty: 'easy',
      },
      {
        question: 'Quel Prophète a été sauvé par Allah lorsque son peuple a voulu le crucifier ?',
        choices: ['Zakariya', 'Issa (Jésus)', 'Yahya', 'Muhammad'],
        correctIndex: 1,
        explanation: 'Le Coran enseigne qu\'Allah a élevé \'Issa vers Lui et qu\'il n\'a été ni tué ni crucifié.',
        difficulty: 'easy',
      },
      {
        question: 'Quel Prophète a pleuré pendant de nombreuses années après avoir perdu de vue son fils Yusuf ?',
        choices: ['Ibrahim', 'Ya\'qub (Jacob)', 'Ishaq', 'Adam'],
        correctIndex: 1,
        explanation: 'Ya\'qub a perdu la vue à force de pleurer son fils Yusuf, avant qu\'Allah ne les réunisse.',
        difficulty: 'easy',
      },
      // === NORMAL ===
      {
        question: 'Quel prophète pouvait parler aux animaux et commander les Djinns ?',
        choices: ['Daoud (عَلَيْهِ ٱلسَّلَامُ)', 'Souleyman (عَلَيْهِ ٱلسَّلَامُ)', 'Idris (عَلَيْهِ ٱلسَّلَامُ)', 'Houd (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 1,
        explanation: 'Allah a accordé à Souleyman (عَلَيْهِ ٱلسَّلَامُ) le pouvoir de comprendre le langage des animaux et de commander les Djinns.',
        difficulty: 'normal',
      },
      {
        question: 'Quel prophète a reçu les Psaumes (Az-Zabour) ?',
        choices: ['Moussa (عَلَيْهِ ٱلسَّلَامُ)', 'Issa (عَلَيْهِ ٱلسَّلَامُ)', 'Daoud (عَلَيْهِ ٱلسَّلَامُ)', 'Ibrahim (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 2,
        explanation: 'Allah a révélé Az-Zabour (les Psaumes) à Daoud (عَلَيْهِ ٱلسَّلَامُ).',
        difficulty: 'normal',
      },
      {
        question: 'Quel prophète a été jeté dans le feu par son peuple ?',
        choices: ['Moussa (عَلَيْهِ ٱلسَّلَامُ)', 'Nouh (عَلَيْهِ ٱلسَّلَامُ)', 'Ibrahim (عَلَيْهِ ٱلسَّلَامُ)', 'Loth (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 2,
        explanation: 'Ibrahim (عَلَيْهِ ٱلسَّلَامُ) a été jeté dans le feu par Nimrod, mais Allah a rendu le feu frais et paisible pour lui.',
        difficulty: 'normal',
      },
      {
        question: 'À quel prophète le livre de l\'Injil (Évangile) a-t-il été révélé ?',
        choices: ['Mohammed (ﷺ)', 'Moussa (عَلَيْهِ ٱلسَّلَامُ)', 'Issa (عَلَيْهِ ٱلسَّلَامُ)', 'Ibrahim (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 2,
        explanation: 'L\'Injil (l\'Évangile originel) a été révélé à Issa (عَلَيْهِ ٱلسَّلَامُ).',
        difficulty: 'normal',
      },
      // === HARD ===
      {
        question: 'Combien de prophètes sont mentionnés par leur nom dans le Coran ?',
        choices: ['20', '25', '30', '33'],
        correctIndex: 1,
        explanation: 'Le Coran mentionne 25 prophètes par leur nom, bien que le nombre total de prophètes envoyés soit bien plus grand.',
        difficulty: 'hard',
      },
      {
        question: 'Quel prophète est décrit dans le Coran comme "Khalilullah" (l\'ami intime d\'Allah) ?',
        choices: ['Moussa (عَلَيْهِ ٱلسَّلَامُ)', 'Mohammed (ﷺ)', 'Ibrahim (عَلَيْهِ ٱلسَّلَامُ)', 'Nouh (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 2,
        explanation: 'Ibrahim (عَلَيْهِ ٱلسَّلَامُ) est surnommé "Khalilullah" (l\'ami intime d\'Allah).',
        difficulty: 'hard',
      },
      {
        question: 'Quel prophète a été élevé au ciel de son vivant?',
        choices: ['Mohammed (ﷺ)', 'Idris (عَلَيْهِ ٱلسَّلَامُ)', 'Issa (عَلَيْهِ ٱلسَّلَامُ)', 'Ilyas (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 2,
        explanation: 'Le Coran dit qu\'Allah a élevé Issa (عَلَيْهِ ٱلسَّلَامُ) vers Lui (Sourate An-Nisa, 4:158) et qu\'il n\'a pas été crucifié.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle sourate du Coran porte le nom d\'un prophète et raconte son histoire en détail, y compris l\'épisode de ses frères ?',
        choices: ['Sourate Ibrahim', 'Sourate Youssouf', 'Sourate Moussa', 'Sourate Houd'],
        correctIndex: 1,
        explanation: 'La sourate Youssouf (sourate 12) raconte en détail l\'histoire de Youssouf (عَلَيْهِ ٱلسَّلَامُ). Allah la qualifie de meilleur récit.',
        difficulty: 'hard',
      },
      {
        question: 'Quel prophète a vécu 950 ans ?',
        choices: ['Adam (عَلَيْهِ ٱلسَّلَامُ)', 'Nouh (عَلَيْهِ ٱلسَّلَامُ)', 'Idris (عَلَيْهِ ٱلسَّلَامُ)', 'Chouayb (عَلَيْهِ ٱلسَّلَامُ)'],
        correctIndex: 1,
        explanation: 'Le Coran mentionne que Nouh (عَلَيْهِ ٱلسَّلَامُ) est resté 950 ans parmi son peuple pour les appeler à Allah (Sourate Al-Ankabout, 29:14).',
        difficulty: 'hard',
      },
      {
        question: 'Quel est le nom de la seule sourate qui ne commence pas par la Basmala (Bismillah) ?',
        choices: ['Sourate At-Tawbah', 'Sourate Al-Anfal', 'Sourate Al-Qiyamah', 'Sourate Al-Hujurat'],
        correctIndex: 0,
        explanation: 'La Sourate At-Tawbah (Sourate 9) est la seule qui ne débute pas par la formule "Bismillah Ar-Rahman Ar-Rahim".',
        difficulty: 'hard'
      },
      {
        question: 'Dans quelle sourate la Basmala (Bismillah) apparaît-elle deux fois ?',
        choices: ['Sourate Al-Baqara', 'Sourate An-Naml', 'Sourate Al-Isra', 'Sourate Al-Alaq'],
        correctIndex: 1,
        explanation: 'Elle apparaît au début de la Sourate An-Naml (27) et à l\'intérieur, au verset 30, dans la lettre du prophète Souleymane.',
        difficulty: 'hard'
      },
      {
        question: 'Quel est le verset le plus long du Coran ?',
        choices: ['Ayat Al-Kursi', 'Le verset de la dette (Al-Dayn)', 'Le dernier verset de la Sourate Al-Fath', 'Le verset du voile'],
        correctIndex: 1,
        explanation: 'Le verset 282 de la Sourate Al-Baqara, appelé "Ayat al-Dayn", est le plus long du Coran.',
        difficulty: 'hard'
      },
      {
        question: 'Combien d\'années la révélation du Coran a-t-elle duré au total ?',
        choices: ['10 ans', '23 ans', '40 ans', '13 ans'],
        correctIndex: 1,
        explanation: 'La révélation a duré environ 23 ans : 13 ans à La Mecque et 10 ans à Médine.',
        difficulty: 'hard'
      },
      {
        question: 'Quelle est la seule sourate qui contient deux versets de "Sajda" (prosternation) ?',
        choices: ['Sourate Al-Hajj', 'Sourate Al-A\'raf', 'Sourate Maryam', 'Sourate Fussilat'],
        correctIndex: 0,
        explanation: 'La Sourate Al-Hajj.',
        difficulty: 'hard'
      },
      {
        question: 'Combien de fois le nom du Prophète Muhammad (ﷺ) est-il explicitement mentionné dans le Coran ?',
        choices: ['4 fois', '5 fois', '25 fois', '12 fois'],
        correctIndex: 0,
        explanation: 'Son nom "Muhammad" apparaît 4 fois (3:144, 33:40, 47:2, 48:29). Il apparaît aussi une fois sous le nom "Ahmad" (61:6).',
        difficulty: 'hard'
      },
      {
        question: 'Combien de prophètes sont mentionnés par leur nom propre dans le Coran ?',
        choices: ['15', '25', '313', '124 000'],
        correctIndex: 1,
        explanation: 'Le Coran mentionne explicitement 25 prophètes par leur nom, d\'Adam (عَلَيْهِ ٱلسَّلَامُ) à Muhammad (ﷺ).',
        difficulty: 'hard'
      },
    ],
  },
  {
    id: 'pillars',
    label: 'Piliers de l\'Islam',
    icon: 'pillar',
    image: require('@/assets/quiz/5pilliers.png'),
    color: '#2E7D32',
    colorLight: '#E8F5E9',
    gradient: ['#2E7D32', '#66BB6A'],
    questions: [
      // === EASY ===
      {
        question: 'Combien y a-t-il de piliers en Islam ?',
        choices: ['3', '4', '5', '6'],
        correctIndex: 2,
        explanation: 'Les 5 piliers sont : la Shahada, la Salat, la Zakat, le Sawm et le Hajj.',
        difficulty: 'easy',
      },
      {
        question: 'Combien de prières obligatoires par jour ?',
        choices: ['3', '4', '5', '7'],
        correctIndex: 2,
        explanation: 'Les 5 prières sont : Fajr, Dhuhr, Asr, Maghrib et Isha.',
        difficulty: 'easy',
      },
      {
        question: 'En quel mois les musulmans jeûnent-ils ?',
        choices: ['Rajab', 'Sha\'ban', 'Ramadan', 'Dhul Hijja'],
        correctIndex: 2,
        explanation: 'Le Ramadan est le 9ème mois du calendrier islamique, durant lequel le Coran a été révélé.',
        difficulty: 'easy',
      },
      {
        question: 'Quel pilier est le pèlerinage à La Mecque ?',
        choices: ['La Zakat', 'Le Hajj', 'La Shahada', 'Le Sawm'],
        correctIndex: 1,
        explanation: 'Le Hajj est obligatoire une fois dans la vie pour tout musulman qui en a les moyens.',
        difficulty: 'easy',
      },
      {
        question: 'Que signifie le mot "Islam" ?',
        choices: ['Méthodologie', 'Soumission (à Allah)', 'Tradition', 'Prophétie'],
        correctIndex: 1,
        explanation: 'L\'Islam signifie la soumission',
        difficulty: 'easy',
      },
      {
        question: 'Combien de fois par jour l\'Adhan (appel à la prière) retentit-il ?',
        choices: ['3 fois', '4 fois', '5 fois', '6 fois'],
        correctIndex: 2,
        explanation: 'Il y a un Adhan pour chacune des 5 prières obligatoires quotidiennes.',
        difficulty: 'easy',
      },
      {
        question: 'Quelle fête célèbre la fin du mois de Ramadan ?',
        choices: ['Eid al-Adha', 'Eid al-Fitr', 'Jumu\'ah', 'Achoura'],
        correctIndex: 1,
        explanation: 'Eid al-Fitr est la fête de la rupture du jeûne qui marque le premier jour du mois de Shawwal.',
        difficulty: 'easy',
      },
      {
        question: 'Comment appelle-t-on la prière du milieu de la journée ?',
        choices: ['Fajr', 'Dhuhr', 'Asr', 'Isha'],
        correctIndex: 1,
        explanation: 'Dhuhr est la prière de midi, effectuée après que le soleil a dépassé le zénith.',
        difficulty: 'easy',
      },
      // === NORMAL ===
      {
        question: 'Quelle est la première partie de la Shahada (Attestation de foi) ?',
        choices: ['Il n\'y a de divinité digne d\'adoration qu\'Allah', 'Muhammad est son messager', 'La prière est obligatoire', 'Le paradis est vérité'],
        correctIndex: 0,
        explanation: 'La Shahada commence par "La ilaha illa Allah" (Il n\'y a de divinité digne d\'adoration qu\'Allah).',
        difficulty: 'normal',
      },
      {
        question: 'Quel est le pourcentage généralement dû pour la Zakat Al-Maal ?',
        choices: ['10%', '2.5%', '5%', '20%'],
        correctIndex: 1,
        explanation: 'Le taux de la Zakat sur les biens accumulés pendant une année lunaire est de 2,5 % au-dessus du Nissab.',
        difficulty: 'normal',
      },
      {
        question: 'Comment s\'appelle la direction vers laquelle les musulmans se tournent pour prier ?',
        choices: ['Le Minaret', 'La Qibla', 'L\'Est', 'Le Mihrab'],
        correctIndex: 1,
        explanation: 'La Qibla est la direction de la Kaaba à La Mecque, vers laquelle les musulmans doivent s\'orienter.',
        difficulty: 'normal',
      },
      {
        question: 'Quel repas prend-on avant l\'aube pour commencer le jeûne ?',
        choices: ['L\'Iftar', 'Le Suhoor', 'Le Walima', 'Le Ghusl'],
        correctIndex: 1,
        explanation: 'Le Suhoor (ou Sahur) est le repas béni pris juste avant l\'appel à la prière du Fajr.',
        difficulty: 'normal',
      },
      {
        question: 'Combien de tours (Tawaf) doit-on effectuer autour de la Kaaba ?',
        choices: ['5', '7', '9', '3'],
        correctIndex: 1,
        explanation: 'Le Tawaf consiste à faire 7 tours autour de la Kaaba dans le sens inverse des aiguilles d\'une montre.',
        difficulty: 'normal',
      },
      {
        question: 'Quelle prière marque la rupture du jeûne pendant le Ramadan ?',
        choices: ['Asr', 'Isha', 'Maghrib', 'Fajr'],
        correctIndex: 2,
        explanation: 'Le jeûne est rompu au coucher du soleil, ce qui correspond au moment de la prière du Maghrib.',
        difficulty: 'normal',
      },
      {
        question: 'Quel est le nom de la prière spéciale effectuée les nuits de Ramadan ?',
        choices: ['Salat al-Janaza', 'Salat al-Eid', 'Salat at-Tarawih', 'Salat ad-Duha'],
        correctIndex: 2,
        explanation: 'Les prières de Tarawih sont des prières surérogatoires spécifiques aux nuits du mois de Ramadan.',
        difficulty: 'normal',
      },
      {
        question: 'Quel terme désigne le seuil de richesse minimum pour devoir payer la Zakat ?',
        choices: ['Le Fiqh', 'Le Nissab', 'La Sadaqa', 'Le Waqf'],
        correctIndex: 1,
        explanation: 'Le Nissab est le montant minimum de richesse qu\'un musulman doit posséder pendant un an pour être redevable de la Zakat.',
        difficulty: 'normal',
      },
      {
        question: 'Quel est le jour le plus important de la semaine pour la prière en commun ?',
        choices: ['Lundi', 'Jeudi', 'Vendredi', 'Samedi'],
        correctIndex: 2,
        explanation: 'Le Vendredi (Jumu\'ah) est le jour de rassemblement hebdomadaire pour la prière collective obligatoire des hommes.',
        difficulty: 'normal',
      },
      {
        question: 'Comment appelle-t-on les ablutions rituelles avant la prière ?',
        choices: ['Woudou', 'Adhan', 'Iqama', 'Takbir'],
        correctIndex: 0,
        explanation: 'Le Woudou (les petites ablutions) est la purification rituelle nécessaire avant d\'accomplir la Salat.',
        difficulty: 'normal',
      },
      {
        question: 'Combien de Rakats (unités de prière) compte la prière du Maghrib ?',
        choices: ['2', '3', '4', '5'],
        correctIndex: 1,
        explanation: 'La prière du Maghrib (au coucher du soleil) est composée de 3 Rakats obligatoires.',
        difficulty: 'normal',
      },
      // === HARD ===
      {
        question: 'Combien de conditions (Shourout) la Shahada "La ilaha illa Allah" possède-t-elle pour être acceptée ?',
        choices: ['3', '5', '7 (ou 8)', '99'],
        correctIndex: 2,
        explanation: 'Les savants ont identifié 7 conditions : La science, la certitude, l\'acceptation, la soumission, la véracité, la sincérité et l\'amour.',
        difficulty: 'hard',
      },
      {
        question: 'Sur quel mont les pèlerins doivent-ils se rassembler pendant le Hajj ?',
        choices: ['Mont Uhud', 'Mont Arafat', 'Mont Sinaï', 'Mont Noor'],
        correctIndex: 1,
        explanation: 'Le stationnement au mont Arafat est le pilier le plus important du Hajj; sans lui, le pèlerinage n\'est pas valide.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle prière ne contient aucune inclinaison (Ruku) ni prosternation (Sujud) ?',
        choices: ['La prière du voyageur', 'La prière mortuaire (Janaza)', 'La prière de l\'éclipse', 'La prière du vendredi'],
        correctIndex: 1,
        explanation: 'La Salat al-Janaza (prière sur le mort) se fait debout et ne comporte ni Ruku ni Sujud.',
        difficulty: 'hard',
      },
      {
        question: 'Le Hajj a lieu pendant quel mois du calendrier islamique ?',
        choices: ['Ramadan', 'Muharram', 'Dhul-Hijja', 'Shawwal'],
        correctIndex: 2,
        explanation: 'Les rites du Hajj s\'accomplissent spécifiquement pendant les premiers jours du mois de Dhul-Hijja.',
        difficulty: 'hard',
      },
      {
        question: 'Comment s\'appelle l\'état de sacralisation nécessaire pour accomplir le Hajj ou la Omra ?',
        choices: ['L\'Ihram', 'Le Ghusl', 'L\'Ihsan', 'Le Niqab'],
        correctIndex: 0,
        explanation: 'L\'Ihram implique de porter des vêtements spécifiques (pour les hommes) et de respecter certains interdits.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle nuit du Ramadan est décrite comme étant "meilleure que 1000 mois" ?',
        choices: ['La nuit du doute', 'La nuit de l\'Ascension', 'Laylat al-Qadr', 'Eid al-Fitr'],
        correctIndex: 2,
        explanation: 'Laylat al-Qadr (la Nuit du Destin) est la nuit où le Coran a été descendu',
        difficulty: 'hard',
      },
      {
        question: 'Entre quelles collines les pèlerins effectuent-ils le Sa\'i (la marche rapide) ?',
        choices: ['Uhud et Badr', 'Safa et Marwa', 'Arafat et Muzdalifa', 'Mina et La Mecque'],
        correctIndex: 1,
        explanation: 'Ce rite commémore la recherche d\'eau par Hajar pour son fils Ismaël.',
        difficulty: 'hard',
      },
      {
        question: 'Que doit faire un musulman s\'il ne trouve pas d\'eau pour ses ablutions ?',
        choices: ['Attendre le lendemain', 'Prier sans ablutions', 'Le Tayammum', 'Juste se laver les mains'],
        correctIndex: 2,
        explanation: 'Le Tayammum est l\'ablution sèche (avec de la terre propre ou de la pierre) qui remplace l\'eau en cas d\'absence ou de maladie.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle sourate est obligatoire de réciter dans chaque Rakat de la prière ?',
        choices: ['Al-Ikhlas', 'Al-Fatiha', 'Al-Falaq', 'An-Nas'],
        correctIndex: 1,
        explanation: 'La récitation de la Sourate Al-Fatiha (L\'Ouverture) est un pilier de la prière; sans elle, la prière n\'est pas valide.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle est la porte du Paradis réservée spécialement aux jeûneurs ?',
        choices: ['Al-Firdaus', 'Al-Amin', 'Ar-Rayyan', 'Bab as-Salam'],
        correctIndex: 2,
        explanation: 'Le Prophète (paix sur lui) a dit que seuls les jeûneurs entreront par la porte Ar-Rayyan le Jour de la Résurrection.',
        difficulty: 'hard',
      },
      {
        question: 'A quel moment doit-on verser Zakat al-Fitr ?',
        choices: ['Après la prière de l\'Aïd', 'Pendant le Hajj', 'Avant la prière de l\'Aïd al-Fitr', 'N\'importe quand dans l\'année'],
        correctIndex: 2,
        explanation: 'Zakat al-Fitr doit être donnée avant la prière de l\'Aïd.',
        difficulty: 'hard',
      },
      {
        question: 'Quel acte marque la fin de l\'état de sacralisation (Ihram) après le Hajj ou la Omra ?',
        choices: ['Se couper les cheveux', 'Prendre une douche', 'Dormir', 'Manger'],
        correctIndex: 0,
        explanation: 'Pour se désacraliser, les hommes se rasent ou se coupent les cheveux, et les femmes coupent une petite mèche.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle invocation dit-on pendant l\'inclinaison (Ruku\') ?',
        choices: ['Allahu Akbar', 'Subhana Rabbiyal Azim', 'Sami Allahu liman hamidah', 'Subhana Rabbiyal A\'la'],
        correctIndex: 1,
        explanation: 'On dit "Gloire à mon Seigneur l\'Immense" (Subhana Rabbiyal Azim) pendant l\'inclinaison.',
        difficulty: 'hard',
      },
      {
        question: 'Quel Prophète a construit la Kaaba avec son fils Ismaël ?',
        choices: ['Adam', 'Nuh (Noé)', 'Ibrahim (Abraham)', 'Moussa (Moïse)'],
        correctIndex: 2,
        explanation: 'C\'est Ibrahim et son fils Ismaël qui ont élevé les fondations de la Maison Sacrée à La Mecque.',
        difficulty: 'hard',
      },
      {
        question: 'Quel est l\'ordre correct des 5 piliers dans le célèbre Hadith de Jibril ?',
        choices: ['Prière, Shahada, Zakat, Jeûne, Hajj', 'Shahada, Prière, Zakat, Jeûne, Hajj', 'Shahada, Jeûne, Prière, Hajj, Zakat', 'Prière, Jeûne, Zakat, Hajj, Shahada'],
        correctIndex: 1,
        explanation: 'Le Prophète (ﷺ) les a cités dans cet ordre : l\'attestation de foi, la prière, la zakat, le jeûne et enfin le pèlerinage.',
        difficulty: 'hard',
      },
      {
        question: 'Combien de fois le mot "Salat" (prière) est-il mentionné dans le Coran ?',
        choices: ['33 fois', '67 fois', '99 fois', '5 fois'],
        correctIndex: 1,
        explanation: 'Le mot "Salat" apparaît 67 fois dans le Coran, soulignant son importance capitale.',
        difficulty: 'hard',
      },
      {
        question: 'Laquelle de ces mosquées est la seule vers laquelle on voyage pour le culte avec Médine et La Mecque ?',
        choices: ['La Mosquée Bleue', 'La Mosquée Al-Aqsa', 'La Mosquée de Quba', 'La Grande Mosquée de Kairouan'],
        correctIndex: 1,
        explanation: 'Le Prophète (ﷺ) a dit que l\'on ne doit entreprendre de voyage (sacré) que vers trois mosquées : Al-Haram, Al-Aqsa et la sienne à Médine.',
        difficulty: 'hard',
      },
      {
        question: 'Pendant le Hajj, quel jour est appelé "Yawm an-Nahr" (le jour du sacrifice) ?',
        choices: ['Le 8 Dhul-Hijja', 'Le 9 Dhul-Hijja', 'Le 10 Dhul-Hijja', 'Le 12 Dhul-Hijja'],
        correctIndex: 2,
        explanation: 'C\'est le 10ème jour de Dhul-Hijja, qui correspond également au jour de l\'Aïd al-Adha.',
        difficulty: 'hard',
      },
      {
        question: 'Quel est le surnom de la ville de Médine, où se trouve la mosquée du Prophète ?',
        choices: ['Al-Quds', 'Al-Munawwarah (La Lumineuse)', 'Al-Amin', 'Al-Bakaa'],
        correctIndex: 1,
        explanation: 'Médine est souvent appelée "Al-Madinah Al-Munawwarah", ce qui signifie la ville illuminée.',
        difficulty: 'hard',
      },
      {
        question: 'Lequel de ces actes n\'est PAS un pilier de l\'Islam mais un pilier de la Foi (Iman) ?',
        choices: ['Donner la Zakat', 'Croire aux Anges', 'Faire le Hajj', 'Prier le Dhuhr'],
        correctIndex: 1,
        explanation: 'La foi aux Anges appartient aux 6 piliers de l\'Iman (la foi).',
        difficulty: 'hard',
      },
      {
        question: 'Dans quelle direction les musulmans priaient-ils AVANT de se tourner vers la Kaaba ?',
        choices: ['Vers Jérusalem (Al-Quds)', 'Vers le lever du soleil', 'Vers Médine', 'Vers le Yémen'],
        correctIndex: 0,
        explanation: 'Au début de l\'Islam, la première Qibla était la mosquée Al-Aqsa à Jérusalem, avant que la révélation ne change la direction vers La Mecque.',
        difficulty: 'hard',
      },
      {
        question: 'Quel est le nom du puits miraculeux situé près de la Kaaba ?',
        choices: ['Puits de Yusuf', 'Puits de Zamzam', 'Puits de Badr', 'Puits de Ridwan'],
        correctIndex: 1,
        explanation: 'Le puits de Zamzam est apparu pour Hajar et son fils Ismaël et ne s\'est jamais tari depuis des millénaires.',
        difficulty: 'hard',
      }
    ],
  },
  {
    id: 'quran',
    label: 'Le Coran',
    icon: 'book-open-page-variant',
    image: require('@/assets/quiz/coran.png'),
    color: '#6A1B9A',
    colorLight: '#F3E5F5',
    gradient: ['#6A1B9A', '#AB47BC'],
    questions: [
      // === EASY ===
      {
        question: 'Quelle est la première sourate du Coran ?',
        choices: ['Al-Baqara', 'Al-Fatiha', 'Al-Ikhlas', 'Al-Falaq'],
        correctIndex: 1,
        explanation: 'Al-Fatiha (L\'Ouverture) est la première sourate. On la récite dans chaque prière.',
        difficulty: 'easy',
      },
      {
        question: 'Combien de sourates y a-t-il dans le Coran ?',
        choices: ['100', '114', '120', '99'],
        correctIndex: 1,
        explanation: 'Le Coran contient 114 sourates, de Al-Fatiha à An-Nas.',
        difficulty: 'easy',
      },
      {
        question: 'En quelle langue le Coran a-t-il été révélé ?',
        choices: ['Hébreu', 'Français', 'Arabe', 'Turc'],
        correctIndex: 2,
        explanation: 'Le Coran a été révélé en arabe au Prophète Mohammed (ﷺ) par l\'ange Jibril.',
        difficulty: 'easy',
      },
      // === NORMAL ===
      {
        question: 'Quelle est la plus longue sourate du Coran ?',
        choices: ['Al-Imran', 'Al-Baqara', 'An-Nisa', 'Al-Maidah'],
        correctIndex: 1,
        explanation: 'Al-Baqara (La Vache) est la plus longue sourate du Coran avec 286 versets.',
        difficulty: 'normal',
      },
      {
        question: 'Quel ange a transmis le Coran au Prophète (ﷺ) ?',
        choices: ['Mikaïl', 'Israfil', 'Jibril', 'Azraïl'],
        correctIndex: 2,
        explanation: 'Jibril (عَلَيْهِ ٱلسَّلَامُ) est l\'ange chargé de transmettre la révélation divine aux prophètes.',
        difficulty: 'normal',
      },
      {
        question: 'Quelle est la dernière sourate du Coran ?',
        choices: ['Al-Ikhlas', 'Al-Falaq', 'An-Nas', 'Al-Kawthar'],
        correctIndex: 2,
        explanation: 'An-Nas (Les Hommes) est la 114ème et dernière sourate du Coran.',
        difficulty: 'normal',
      },
      {
        question: 'Combien de Juz\' (parties) le Coran comporte-t-il ?',
        choices: ['20', '25', '30', '40'],
        correctIndex: 2,
        explanation: 'Le Coran est divisé en 30 Juz\' (parties) pour faciliter sa lecture en un mois.',
        difficulty: 'normal',
      },
      // === HARD ===
      {
        question: 'Quel est le verset le plus long du Coran ?',
        choices: ['Ayat al-Kursi (2:255)', 'Le verset de la dette (2:282)', 'Le verset de la lumière (24:35)', 'Le verset du Trône (2:256)'],
        correctIndex: 1,
        explanation: 'Le verset de la dette (Al-Baqara, 2:282) est le plus long verset du Coran. Il détaille les règles d\'écriture des contrats de dette.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle sourate est appelée "le cœur du Coran" ?',
        choices: ['Al-Fatiha', 'Al-Baqara', 'Ya-Sin', 'Ar-Rahman'],
        correctIndex: 2,
        explanation: 'Le Prophète (ﷺ) a dit : "Tout a un cœur, et le cœur du Coran est Ya-Sin." (Rapporté par At-Tirmidhi)',
        difficulty: 'hard',
      },
      {
        question: 'Combien d\'années a duré la révélation complète du Coran ?',
        choices: ['10 ans', '15 ans', '23 ans', '30 ans'],
        correctIndex: 2,
        explanation: 'Le Coran a été révélé progressivement sur une période de 23 ans (610-632), à La Mecque puis à Médine.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle sourate ne commence PAS par "Bismillah Ar-Rahman Ar-Rahim" ?',
        choices: ['Al-Fatiha', 'At-Tawba', 'Al-Ikhlas', 'Al-Falaq'],
        correctIndex: 1,
        explanation: 'La sourate At-Tawba (Le Repentir, sourate 9) est la seule sourate qui ne commence pas par la Basmala.',
        difficulty: 'hard',
      },
      {
        question: 'Quel calife a ordonné la compilation officielle du Coran en un seul livre (Mushaf) ?',
        choices: ['Abu Bakr (رضي الله عنه)', 'Umar (رضي الله عنه)', 'Uthman (رضي الله عنه)', 'Ali (رضي الله عنه)'],
        correctIndex: 0,
        explanation: 'Abu Bakr (رضي الله عنه) a ordonné la première compilation après la bataille de Yamama. Uthman (رضي الله عنه) a ensuite standardisé les copies.',
        difficulty: 'hard',
      },
    ],
  },
  {
    id: 'sira',
    label: 'Le Prophète (ﷺ)',
    icon: 'mosque',
    image: require('@/assets/quiz/muhammed.png'),
    color: '#E65100',
    colorLight: '#FFF3E0',
    gradient: ['#E65100', '#FFA726'],
    questions: [
      // === EASY ===
      {
        question: 'Dans quelle ville est né le Prophète (ﷺ) ?',
        choices: ['Médine', 'Jérusalem', 'La Mecque', 'Taïf'],
        correctIndex: 2,
        explanation: 'Le Prophète (ﷺ) est né à La Mecque en l\'an 570 de l\'ère chrétienne.',
        difficulty: 'easy',
      },
      {
        question: 'Comment s\'appelle la migration du Prophète (ﷺ) vers Médine ?',
        choices: ['Le Hajj', 'L\'Hégire', 'L\'Isra', 'Le Miraj'],
        correctIndex: 1,
        explanation: 'L\'Hégire (622) marque le début du calendrier islamique (Hijri).',
        difficulty: 'easy',
      },
      {
        question: 'Quel était le métier du Prophète (ﷺ) avant la révélation ?',
        choices: ['Forgeron', 'Berger et commerçant', 'Agriculteur', 'Pêcheur'],
        correctIndex: 1,
        explanation: 'Le Prophète (ﷺ) était berger dans sa jeunesse puis commerçant. Il était connu pour son honnêteté (Al-Amine).',
        difficulty: 'easy',
      },
      // === NORMAL ===
      {
        question: 'Quel était le surnom du Prophète (ﷺ) avant la prophétie ?',
        choices: ['Al-Amine (le digne de confiance)', 'Al-Farouq (celui qui distingue)', 'As-Siddiq (le véridique)', 'Dhul-Nurayn (celui aux deux lumières)'],
        correctIndex: 0,
        explanation: 'Le Prophète (ﷺ) était surnommé "Al-Amine" (le digne de confiance) par les Mecquois en raison de sa grande honnêteté.',
        difficulty: 'normal',
      },
      {
        question: 'Comment s\'appelle la première épouse du Prophète (ﷺ) ?',
        choices: ['Aïcha (رضي الله عنها)', 'Khadija (رضي الله عنها)', 'Hafsa (رضي الله عنها)', 'Fatima (رضي الله عنها)'],
        correctIndex: 1,
        explanation: 'Khadija bint Khuwaylid (رضي الله عنها) fut la première épouse du Prophète (ﷺ) et la première personne à embrasser l\'Islam.',
        difficulty: 'normal',
      },
      {
        question: 'Dans quelle grotte le Prophète (ﷺ) a-t-il reçu la première révélation ?',
        choices: ['Grotte de Thawr', 'Grotte de Hira', 'Grotte de Uhud', 'Grotte de Badr'],
        correctIndex: 1,
        explanation: 'Le Prophète (ﷺ) méditait dans la grotte de Hira sur le mont Nour lorsque Jibril lui est apparu pour la première fois.',
        difficulty: 'normal',
      },
      {
        question: 'Quel compagnon accompagnait le Prophète (ﷺ) lors de l\'Hégire vers Médine ?',
        choices: ['Umar ibn al-Khattab', 'Ali ibn Abi Talib', 'Abu Bakr as-Siddiq', 'Uthman ibn Affan'],
        correctIndex: 2,
        explanation: 'Abu Bakr as-Siddiq (رضي الله عنه) accompagna le Prophète (ﷺ) et ils se cachèrent dans la grotte de Thawr.',
        difficulty: 'normal',
      },
      // === HARD ===
      {
        question: 'Quel âge avait le Prophète (ﷺ) quand il a reçu la première révélation ?',
        choices: ['25 ans', '30 ans', '40 ans', '45 ans'],
        correctIndex: 2,
        explanation: 'Le Prophète (ﷺ) avait 40 ans lorsqu\'il reçut la première révélation dans la grotte de Hira en 610.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle fut la première bataille de l\'Islam ?',
        choices: ['La bataille de Uhud', 'La bataille de Badr', 'La bataille de Khandaq', 'La bataille de Hunayn'],
        correctIndex: 1,
        explanation: 'La bataille de Badr (2ème année de l\'Hégire, 624) fut la première grande bataille entre les musulmans et les Quraychites.',
        difficulty: 'hard',
      },
      {
        question: 'Quel est le nom du voyage nocturne du Prophète (ﷺ) de La Mecque à Jérusalem ?',
        choices: ['Le Miraj', 'L\'Isra', 'L\'Hégire', 'Le Hajj'],
        correctIndex: 1,
        explanation: 'L\'Isra est le voyage nocturne de La Mecque à Al-Aqsa (Jérusalem). Le Miraj est l\'ascension vers les cieux qui a suivi.',
        difficulty: 'hard',
      },
      {
        question: 'En quelle année le Prophète (ﷺ) a-t-il conquis La Mecque pacifiquement ?',
        choices: ['6ème année de l\'Hégire', '8ème année de l\'Hégire', '10ème année de l\'Hégire', '4ème année de l\'Hégire'],
        correctIndex: 1,
        explanation: 'La conquête de La Mecque (Fath Makkah) eut lieu en l\'an 8 de l\'Hégire (630). Le Prophète (ﷺ) a pardonné aux Mecquois.',
        difficulty: 'hard',
      },
      {
        question: 'Combien d\'enfants le Prophète (ﷺ) a-t-il eus avec Khadija (رضي الله عنها) ?',
        choices: ['4', '5', '6', '7'],
        correctIndex: 2,
        explanation: 'Le Prophète (ﷺ) a eu 6 enfants avec Khadija : Al-Qasim, Zaynab, Ruqayya, Umm Kulthum, Fatima et Abdullah.',
        difficulty: 'hard',
      },
    ],
  },
  {
    id: 'tawhid',
    label: 'Tawhid (Unicité)',
    icon: 'shield-star',
    image: require('@/assets/quiz/tawhid.png'),
    color: '#00695C',
    colorLight: '#E0F2F1',
    gradient: ['#00695C', '#4DB6AC'],
    questions: [
      // === EASY ===
      {
        question: 'Que signifie le mot "Tawhid" ?',
        choices: ['La prière', 'L\'unicité d\'Allah', 'Le pèlerinage', 'Le jeûne'],
        correctIndex: 1,
        explanation: 'Le Tawhid vient de la racine arabe "Wahid" qui signifie "Un". C\'est le fait de reconnaître qu\'Allah est l\'Unique.',
        difficulty: 'easy',
      },
      {
        question: 'Quelle est la première partie de la Chahada ?',
        choices: ['Allahu Akbar', 'SubhanAllah', 'La ilaha illa Allah', 'Alhamdulillah'],
        correctIndex: 2,
        explanation: '"La ilaha illa Allah" signifie "Nulle divinité n\'est digne d\'être adorée en dehors d\'Allah".',
        difficulty: 'easy',
      },
      {
        question: 'Combien de catégories principales de Tawhid les savants mentionnent-ils ?',
        choices: ['Une seule', 'Deux', 'Trois', 'Cinq'],
        correctIndex: 2,
        explanation: 'Les savants mentionnent généralement trois catégories : Tawhid ar-Rububiyyah, Tawhid al-Uluhiyyah et Tawhid al-Asma wa-Sifat.',
        difficulty: 'easy',
      },
      {
        question: 'Que signifie Tawhid ar-Rububiyyah ?',
        choices: ['Unifier Allah dans Ses Noms', 'Unifier Allah dans Sa Seigneurie', 'Unifier Allah dans l\'adoration', 'Unifier les musulmans'],
        correctIndex: 1,
        explanation: 'Tawhid ar-Rububiyyah signifie reconnaître qu\'Allah est le seul Créateur, Maître et Seigneur de toute chose.',
        difficulty: 'easy',
      },
      {
        question: 'Que signifie Tawhid al-Uluhiyyah ?',
        choices: ['Unifier Allah dans l\'adoration', 'Unifier Allah dans la création', 'Unifier Allah dans sa seigneurie', 'Unifier Allah dans ses noms et attributs'],
        correctIndex: 0,
        explanation: 'Tawhid al-Uluhiyyah consiste à vouer toutes les adorations uniquement à Allah, sans rien Lui associer.',
        difficulty: 'easy',
      },
      {
        question: 'Que signifie Tawhid al-Asma wa-Sifat ?',
        choices: ['Unifier Allah dans l\'adoration', 'Unifier Allah dans la création', 'Unifier Allah dans Ses Noms et Attributs', 'Unifier Allah dans sa seigneurie'],
        correctIndex: 2,
        explanation: 'Cela signifie affirmer les Noms et Attributs d\'Allah tels qu\'ils sont venus dans le Coran et la Sunnah, sans les déformer.',
        difficulty: 'easy',
      },
      {
        question: 'Quel est le plus grand péché en islam ?',
        choices: ['Le mensonge', 'Le vol', 'Le shirk', 'L\'orgueil'],
        correctIndex: 2,
        explanation: 'Le plus grand péché est le shirk, qui consiste à associer une autre divinité à Allah.',
        difficulty: 'easy',
      },
      {
        question: 'Que signifie le mot "shirk" ?',
        choices: ['L\'obéissance', 'L\'association à Allah', 'La prière nocturne', 'La charité'],
        correctIndex: 1,
        explanation: 'Le shirk signifie donner un associé à Allah dans ce qui Lui est propre, comme l\'adoration.',
        difficulty: 'easy',
      },
      {
        question: 'Quelle est la base de l\'appel de tous les prophètes ?',
        choices: ['L\'appel au commerce', 'L\'appel à l\'unicité d\'Allah', 'L\'appel à la prière', 'L\'appel à faire le hadj'],
        correctIndex: 1,
        explanation: 'Tous les prophètes ont appelé leur peuple à adorer Allah seul sans rien Lui associer.',
        difficulty: 'easy',
      },
      {
        question: 'Dire "La ilaha illa Allah" signifie :',
        choices: ['Il n\'y a pas de créateur sauf Allah', 'Il n\'y a pas de seigneur sauf Allah', 'Il n\'y a pas de divinité digne d\'adoration sauf Allah', 'Il n\'y a pas de juge sauf Allah'],
        correctIndex: 2,
        explanation: 'La signification correcte est qu\'il n\'y a aucune divinité digne d\'adoration en dehors d\'Allah.',
        difficulty: 'easy',
      },
      {
        question: 'Le Tawhid est-il la première chose à laquelle les prophètes ont appelé ?',
        choices: ['Oui', 'Non', 'Seulement certains prophètes', 'Seulement Muhammad ﷺ'],
        correctIndex: 0,
        explanation: 'Oui, le Tawhid est la première chose à laquelle tous les prophètes ont appelé leurs peuples.',
        difficulty: 'easy',
      },
      {
        question: 'Qui est le seul Créateur de toute chose ?',
        choices: ['Les anges', 'Les prophètes', 'Allah', 'Les humains'],
        correctIndex: 2,
        explanation: 'Allah est le seul Créateur, Maître et Seigneur de toute chose. Cela fait partie du Tawhid ar-Rububiyyah.',
        difficulty: 'easy',
      },
      {
        question: 'Adorer autre qu\'Allah est appelé :',
        choices: ['Tawhid', 'Sunnah', 'Shirk', 'Sadaqah'],
        correctIndex: 2,
        explanation: 'Adorer autre qu\'Allah est du shirk, c\'est-à-dire associer un partenaire à Allah.',
        difficulty: 'easy',
      },
      {
        question: 'Faire une invocation (dou\'a) doit être adressé à :',
        choices: ['Un prophète', 'Un ange', 'Un pieux', 'Allah seul'],
        correctIndex: 3,
        explanation: 'L\'invocation est un acte d\'adoration qui doit être voué uniquement à Allah.',
        difficulty: 'easy',
      },
      {
        question: 'Le Tawhid concerne principalement :',
        choices: ['Les bonnes manières', 'L\'unicité d\'Allah', 'Le commerce', 'La politique'],
        correctIndex: 1,
        explanation: 'Le Tawhid concerne l\'unicité d\'Allah dans Sa Seigneurie, Son adoration et Ses Noms et Attributs.',
        difficulty: 'easy',
      },
      {
        question: 'Reconnaître qu\'Allah est le seul à donner la vie et la mort relève de :',
        choices: ['Tawhid ar-Rububiyyah', 'Tawhid al-Uluhiyyah', 'Tawhid al-Asma wa-Sifat', 'Le fiqh'],
        correctIndex: 0,
        explanation: 'Donner la vie et la mort fait partie de la Seigneurie d\'Allah, ce qui relève du Tawhid ar-Rububiyyah.',
        difficulty: 'easy',
      },
      {
        question: 'Consacrer la prière uniquement à Allah relève de :',
        choices: ['Tawhid al-Uluhiyyah', 'Tawhid ar-Rububiyyah', 'La langue arabe', 'L\'histoire islamique'],
        correctIndex: 0,
        explanation: 'Vouer les actes d\'adoration comme la prière uniquement à Allah relève du Tawhid al-Uluhiyyah.',
        difficulty: 'easy',
      },
      {
        question: 'Croire qu\'Allah entend et voit toute chose relève de :',
        choices: ['Tawhid al-Asma wa-Sifat', 'Tawhid ar-Rububiyyah', 'Le jeûne', 'La zakat'],
        correctIndex: 0,
        explanation: 'Affirmer qu\'Allah entend et voit toute chose fait partie de Ses Noms et Attributs.',
        difficulty: 'easy',
      },
      {
        question: 'Le message principal du Coran est :',
        choices: ['Les histoires anciennes', 'Les règles commerciales', 'Le Tawhid', 'La médecine'],
        correctIndex: 2,
        explanation: 'Le thème central du Coran est l\'appel à l\'unicité d\'Allah et au rejet du shirk.',
        difficulty: 'easy',
      },
      {
        question: 'Jurer par autre qu\'Allah est :',
        choices: ['Recommandé', 'Permis', 'Une forme de shirk', 'Obligatoire'],
        correctIndex: 2,
        explanation: 'Jurer par autre qu\'Allah est interdit et peut être une forme de shirk mineur.',
        difficulty: 'easy',
      },
      {
        question: 'Le Tawhid est-il la base de l\'Islam ?',
        choices: ['Oui', 'Non', 'Seulement pour les savants', 'Seulement à Médine'],
        correctIndex: 0,
        explanation: 'Oui, le Tawhid est la base et le fondement de toute la religion islamique.',
        difficulty: 'easy',
      },
      {
        question: 'Égorgé une bête en cherchant la bénédiction d\'autre qu\'Allah est :',
        choices: ['Un acte recommandé', 'Un simple péché', 'Un acte culturel sans gravité', 'Un acte de shirk majeur'],
        correctIndex: 3,
        explanation: 'L\'égorgement est un acte d\'adoration. Le consacrer à autre qu\'Allah constitue un shirk majeur.',
        difficulty: 'easy',
      },
      {
        question: 'Invoquer un mort pour lui demander de l\'aide est :',
        choices: ['Permis si la personne était pieuse', 'Un acte de respect', 'Du shirk', 'Une simple innovation'],
        correctIndex: 2,
        explanation: 'L\'invocation est une adoration qui doit être adressée uniquement à Allah. L\'adresser à un mort est du shirk.',
        difficulty: 'easy',
      },
      {
        question: 'Faire un vœu (nadhr) pour autre qu\'Allah est :',
        choices: ['Autorisé en cas de difficulté', 'Une adoration vouée à autre qu\'Allah', 'Recommandé pour les saints', 'Un acte neutre'],
        correctIndex: 1,
        explanation: 'Le vœu est un acte d\'adoration. Le diriger vers autre qu\'Allah constitue une forme de shirk.',
        difficulty: 'easy',
      },
      {
        question: 'Porter un porte-bonheur en pensant qu\'il protège du mal est :',
        choices: ['Un simple bijou', 'Un acte de Tawhid', 'Une forme de shirk', 'Une obligation'],
        correctIndex: 2,
        explanation: 'Croire qu\'un objet protège du mal relève du shirk, car la protection appartient uniquement à Allah.',
        difficulty: 'easy',
      },
      {
        question: 'Accrocher une "main de Fatma" pour se protéger du mauvais œil est :',
        choices: ['Une tradition recommandée', 'Une forme de superstition et relève du shirk', 'Un acte obligatoire', 'Un pilier de l\'Islam'],
        correctIndex: 1,
        explanation: 'Attribuer un pouvoir de protection à un objet est une forme de superstition et relève du shirk.',
        difficulty: 'easy',
      },
      {
        question: 'Croire qu\'un trèfle à quatre feuilles apporte la chance est :',
        choices: ['Un acte scientifique', 'Une croyance permise', 'Une forme de superstition et relève du shirk', 'Un acte d\'adoration'],
        correctIndex: 2,
        explanation: 'Attribuer la chance à un objet est une superstition qui contredit le Tawhid et relève du shirk.',
        difficulty: 'easy',
      },
      {
        question: 'Demander à un saint absent d\'exaucer un besoin est :',
        choices: ['Permis s\'il était pieux', 'Un acte culturel', 'Une forme de shirk', 'Un acte méritoire'],
        correctIndex: 2,
        explanation: 'Seul Allah exauce les invocations. Demander cela à autre que Lui constitue du shirk.',
        difficulty: 'easy',
      },
      {
        question: 'Croire qu\'une amulette éloigne les maladies par elle-même est :',
        choices: ['Une protection naturelle', 'Une forme de shirk', 'Une simple médecine', 'Une obligation religieuse'],
        correctIndex: 1,
        explanation: 'Attribuer à une amulette un pouvoir indépendant de protection est une forme de shirk.',
        difficulty: 'easy',
      },
      {
        question: 'Faire un sacrifice au nom d\'un djinn est :',
        choices: ['Un acte culturel ancien', 'Un acte permis en voyage', 'Un acte de shirk majeur', 'Une simple erreur'],
        correctIndex: 2,
        explanation: 'Le sacrifice est une adoration qui doit être vouée uniquement à Allah. Le faire pour un djinn est du shirk majeur.',
        difficulty: 'easy',
      },


      // === NORMAL ===
      {
        question: 'Comment appelle-t-on le fait d\'associer un partenaire à Allah ?',
        choices: ['Le Koufr', 'Le Chirk', 'Le Nifaq', 'Le Fisq'],
        correctIndex: 1,
        explanation: 'Le Chirk est l\'opposé du Tawhid. C\'est le péché le plus grave en Islam car il brise le principe d\'unicité.',
        difficulty: 'normal',
      },
      {
        question: 'Quel type de Tawhid concerne l\'unicité d\'Allah dans Ses actes (Création, Subsistance) ?',
        choices: ['Tawhid al-Uluhiyyah', 'Tawhid al-Asma wa Sifat', 'Tawhid ar-Rububiyyah', 'Tawhid al-Ibadah'],
        correctIndex: 2,
        explanation: 'Le Tawhid ar-Rububiyyah est la reconnaissance qu\'Allah est le seul Seigneur.',
        difficulty: 'normal',
      },
      {
        question: 'Quelle est la différence principale entre le shirk majeur et le shirk mineur ?',
        choices: ['Le shirk mineur fait sortir de l\'Islam', 'Le shirk majeur annule toutes les œuvres et fait sortir de l\'Islam', 'Ils sont identiques', 'Le shirk majeur est seulement un petit péché'],
        correctIndex: 1,
        explanation: 'Le shirk majeur fait sortir de l\'Islam et annule les œuvres, tandis que le shirk mineur est un grand péché mais ne fait pas sortir de l\'Islam.',
        difficulty: 'normal',
      },
      {
        question: 'Sacrifier pour autre qu\'Allah tout en croyant qu\'Allah est le Créateur relève de quelle catégorie ?',
        choices: ['Tawhid ar-Rububiyyah', 'Shirk dans l\'adoration (Uluhiyyah)', 'Une simple innovation', 'Un acte recommandé'],
        correctIndex: 1,
        explanation: 'Même si la personne reconnaît qu\'Allah est le Créateur, diriger un acte d\'adoration vers autre que Lui est un shirk dans l\'Uluhiyyah.',
        difficulty: 'normal',
      },
      {
        question: 'Le fait de porter une amulette en croyant qu\'elle protège par la permission d\'Allah est :',
        choices: ['Du Tawhid complet', 'Du shirk mineur', 'Du shirk majeur', 'Une obligation'],
        correctIndex: 1,
        explanation: 'Attribuer une cause qu\'Allah n\'a pas légiférée comme moyen de protection est considéré comme du shirk mineur.',
        difficulty: 'normal',
      },
      {
        question: 'Faire une invocation à Allah mais en passant par un mort pour qu\'il transmette la demande est :',
        choices: ['Un acte recommandé', 'Une forme de shirk majeur', 'Un simple péché mineur', 'Une bonne innovation'],
        correctIndex: 1,
        explanation: 'L\'invocation est une adoration directe. La diriger vers un mort ou lui demander d\'intervenir constitue du shirk majeur.',
        difficulty: 'normal',
      },
      {
        question: 'Jurer par le Prophète ﷺ est classé comme :',
        choices: ['Permis', 'Shirk mineur', 'Shirk majeur', 'Obligatoire'],
        correctIndex: 1,
        explanation: 'Jurer par autre qu\'Allah est considéré comme du shirk mineur car le serment est une forme de glorification.',
        difficulty: 'normal',
      },
      {
        question: 'Croire qu\'un saint connaît l\'invisible est :',
        choices: ['Une marque de respect', 'Du Tawhid', 'Du shirk majeur', 'Une simple erreur sans gravité'],
        correctIndex: 2,
        explanation: 'La connaissance de l\'invisible appartient uniquement à Allah. L\'attribuer à une créature est du shirk majeur.',
        difficulty: 'normal',
      },
      {
        question: 'Faire une œuvre pour être vu et admiré par les gens (riyâ) est :',
        choices: ['Du shirk mineur', 'Du shirk majeur', 'Une obligation sociale', 'Un acte recommandé'],
        correctIndex: 0,
        explanation: 'Le riyâ consiste à faire une adoration pour être vu. Il est considéré comme une forme de shirk mineur.',
        difficulty: 'normal',
      },
      {
        question: 'Chercher la bénédiction d\'une pierre ou d\'un arbre en pensant qu\'ils possèdent un pouvoir est :',
        choices: ['Un acte culturel permis', 'Du shirk majeur', 'Une simple habitude', 'Un acte recommandé'],
        correctIndex: 1,
        explanation: 'Attribuer un pouvoir de bénédiction à une chose sans preuve révélée relève du shirk majeur.',
        difficulty: 'normal',
      },
      {
        question: 'Croire qu\'une cause agit indépendamment de la volonté d\'Allah est :',
        choices: ['Du Tawhid parfait', 'Du shirk majeur', 'Une simple erreur scientifique', 'Un acte recommandé'],
        correctIndex: 1,
        explanation: 'Penser qu\'une cause agit de manière autonome sans la volonté d\'Allah contredit le Tawhid et relève du shirk majeur.',
        difficulty: 'normal',
      },
      {
        question: 'Quel était le premier message que les prophètes adressaient à leur peuple ?',
        choices: ['Établir un commerce juste', 'Appeler au Tawhid', 'Organiser la société', 'Enseigner la médecine'],
        correctIndex: 1,
        explanation: 'Tous les prophètes ont commencé par appeler leur peuple à adorer Allah seul et à délaisser le shirk.',
        difficulty: 'normal',
      },
      {
        question: 'Pourquoi l\'appel au Tawhid précède-t-il les autres obligations ?',
        choices: ['Parce qu\'il est facultatif', 'Parce qu\'il est la base sur laquelle reposent toutes les œuvres', 'Parce qu\'il concerne uniquement les savants', 'Parce qu\'il est secondaire'],
        correctIndex: 1,
        explanation: 'Le Tawhid est le fondement. Sans lui, les actes d\'adoration ne sont pas valides.',
        difficulty: 'normal',
      },
      {
        question: 'Affirmer les Noms et Attributs d\'Allah sans les déformer ni les nier correspond à :',
        choices: ['La négation totale', 'La voie des pieux prédécesseurs', 'Une innovation récente', 'Une interprétation philosophique'],
        correctIndex: 1,
        explanation: 'La compréhension des pieux prédécesseurs consiste à affirmer ce qu\'Allah a affirmé pour Lui-même, sans altération, négation, ni assimilation.',
        difficulty: 'normal',
      },
      {
        question: 'Nier un Nom qu\'Allah S\'est attribué dans le Coran relève de :',
        choices: ['Un acte recommandé', 'Une simple erreur linguistique', 'Une contradiction dans le Tawhid des Noms et Attributs', 'Une bonne intention'],
        correctIndex: 2,
        explanation: 'Nier un Nom ou un Attribut affirmé par les textes contredit le Tawhid al-Asma wa-Sifat.',
        difficulty: 'normal',
      },
      {
        question: 'Comparer les Attributs d\'Allah à ceux des créatures est :',
        choices: ['Une bonne explication', 'Une forme d\'assimilation interdite', 'Un acte méritoire', 'Une obligation théologique'],
        correctIndex: 1,
        explanation: 'Assimiler les Attributs d\'Allah à ceux des créatures est interdit, car rien ne Lui ressemble.',
        difficulty: 'normal',
      },
      {
        question: 'Dire qu\'Allah entend et voit, sans comparer à la création, relève de :',
        choices: ['Tawhid al-Asma wa-Sifat', 'Shirk majeur', 'Une simple métaphore', 'Une innovation blâmable'],
        correctIndex: 0,
        explanation: 'Affirmer qu\'Allah entend et voit comme Il convient à Sa majesté fait partie du Tawhid des Noms et Attributs.',
        difficulty: 'normal',
      },
      {
        question: 'L\'appel au Tawhid implique aussi de délaisser :',
        choices: ['Le commerce', 'Les études', 'Le shirk sous toutes ses formes', 'Les relations sociales'],
        correctIndex: 2,
        explanation: 'Appeler au Tawhid signifie appeler à adorer Allah seul et à abandonner toute forme de shirk.',
        difficulty: 'normal',
      },
      {
        question: 'Interpréter tous les Attributs d\'Allah de manière figurée sans preuve relève de :',
        choices: ['La méthodologie des salaf', 'Une altération des textes', 'Une obligation religieuse', 'Une preuve de piété'],
        correctIndex: 1,
        explanation: 'Déformer le sens apparent des Attributs sans preuve est considéré comme une altération contraire à la voie des pieux prédécesseurs.',
        difficulty: 'normal',
      },
      {
        question: 'Connaître les Noms d\'Allah et invoquer Allah par eux fait partie de :',
        choices: ['Une simple culture générale', 'Tawhid al-Asma wa-Sifat', 'Une innovation moderne', 'Une obligation sociale'],
        correctIndex: 1,
        explanation: 'Apprendre les Noms d\'Allah, les comprendre et invoquer Allah par eux relève du Tawhid des Noms et Attributs.',
        difficulty: 'normal',
      },
      {
        question: 'Celui qui appelle au Tawhid doit commencer par :',
        choices: ['Les sujets politiques', 'Les divergences secondaires', 'La correction de la croyance', 'Les détails juridiques'],
        correctIndex: 2,
        explanation: 'La priorité dans l\'appel est la rectification de la croyance et l\'unicité d\'Allah avant les autres aspects.',
        difficulty: 'normal',
      },

      // === HARD ===
      {
        question: 'Quelle est la différence entre le Tawhid ar-Rububiyyah et le Tawhid al-Uluhiyyah ?',
        choices: [
          'Il n\'y a aucune différence',
          'L\'un concerne les Noms et l\'autre les Attributs',
          'Le premier concerne les actes d\'Allah, le second les actes d\'adoration des créatures',
          'Le premier est pour les anges, le second pour les hommes'
        ],
        correctIndex: 2,
        explanation: 'Ar-Rububiyyah concerne ce qu\'Allah fait (créer, nourrir), tandis que Al-Uluhiyyah concerne ce que nous faisons pour Lui (prier, sacrifier).',
        difficulty: 'hard',
      },
      {
        question: 'Quel type de Chirk est décrit comme étant "plus caché que le pas d\'une fourmi noire sur une pierre noire" ?',
        choices: ['Le Chirk majeur', 'Le Chirk mineur (Ar-Riya)', 'L\'apostasie', 'L\'hypocrisie'],
        correctIndex: 1,
        explanation: 'Il s\'agit d\'Ar-Riya (l\'ostentation), faire une bonne action pour être vu des gens. C\'est un Chirk mineur très subtil.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle est la condition indispensable pour que l\'attestation "La ilaha illa Allah" soit valide ?',
        choices: ['La prononcer uniquement avec la langue', 'La comprendre, l\'accepter et agir selon elle', 'La répéter un grand nombre de fois', 'L\'écrire et la porter sur soi'],
        correctIndex: 1,
        explanation: 'La simple prononciation ne suffit pas. Elle nécessite la connaissance, la certitude, l\'acceptation, la sincérité et l\'application, conformément à sa signification.',
        difficulty: 'hard',
      },
      {
        question: 'En quoi le Tawhid al-Uluhiyyah implique-t-il nécessairement le Tawhid ar-Rububiyyah ?',
        choices: ['Parce qu\'ils sont totalement séparés', 'Parce que reconnaître Allah comme seul digne d\'adoration implique qu\'Il est le seul Seigneur', 'Parce que l\'Uluhiyyah annule la Rububiyyah', 'Il n\'y a aucun lien entre eux'],
        correctIndex: 1,
        explanation: 'Celui qui reconnaît qu\'Allah seul mérite l\'adoration reconnaît nécessairement qu\'Il est le seul Créateur et Maître. L\'Uluhiyyah inclut la Rububiyyah.',
        difficulty: 'hard',
      },
      {
        question: 'Attribuer à une créature un Attribut propre exclusivement à Allah, comme la connaissance absolue de l\'invisible, relève de :',
        choices: ['Shirk dans la Rububiyyah', 'Shirk dans les Noms et Attributs', 'Une simple exagération', 'Un acte recommandé'],
        correctIndex: 1,
        explanation: 'Attribuer un Attribut exclusif d\'Allah à une créature constitue un shirk dans le Tawhid al-Asma wa-Sifat.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle est la position correcte concernant les textes relatifs aux Attributs d\'Allah ?',
        choices: ['Les nier totalement', 'Les interpréter systématiquement de manière figurée', 'Les affirmer tels qu\'ils sont venus, sans altération ni assimilation', 'Les comparer aux attributs humains'],
        correctIndex: 2,
        explanation: 'La voie des pieux prédécesseurs consiste à affirmer les Attributs tels qu\'ils sont rapportés, sans les déformer, sans les nier, sans demander comment et sans les comparer.',
        difficulty: 'hard',
      },
      {
        question: 'Celui qui accomplit des actes d\'adoration tout en commettant du shirk majeur verra ses œuvres :',
        choices: ['Acceptées partiellement', 'Multipliées', 'Annulées', 'Reportées'],
        correctIndex: 2,
        explanation: 'Le shirk majeur annule l\'ensemble des œuvres et fait sortir de l\'Islam.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle est la différence essentielle entre le riyâ et le shirk majeur ?',
        choices: ['Le riyâ fait sortir de l\'Islam', 'Le riyâ est un shirk mineur qui ne fait pas sortir de l\'Islam', 'Ils sont identiques', 'Le shirk majeur est plus léger'],
        correctIndex: 1,
        explanation: 'Le riyâ est une forme de shirk mineur car l\'adoration est entachée par l\'ostentation, mais il ne fait pas sortir de l\'Islam.',
        difficulty: 'hard',
      },
      {
        question: 'Pourquoi les polythéistes de Quraysh n\'étaient-ils pas considérés comme croyants malgré leur reconnaissance qu\'Allah est le Créateur ?',
        choices: ['Parce qu\'ils niaient totalement Allah', 'Parce qu\'ils rejetaient le Tawhid al-Uluhiyyah', 'Parce qu\'ils priaient trop', 'Parce qu\'ils ignoraient la langue arabe'],
        correctIndex: 1,
        explanation: 'Ils reconnaissaient la Seigneurie d\'Allah mais associaient d\'autres divinités dans l\'adoration, ce qui contredit le Tawhid al-Uluhiyyah.',
        difficulty: 'hard',
      },
    ],
  },
  {
    id: 'manners',
    label: 'Bonnes manières',
    icon: 'hand-heart',
    image: require('@/assets/quiz/bonnemaniere.png'),
    color: '#C62828',
    colorLight: '#FFEBEE',
    gradient: ['#C62828', '#EF5350'],
    questions: [
      // === EASY ===
      {
        question: 'Que dit-on avant de manger ?',
        choices: ['Alhamdulillah', 'SubhanAllah', 'Bismillah', 'Allahu Akbar'],
        correctIndex: 2,
        explanation: 'On dit "Bismillah" (Au nom d\'Allah) avant de commencer à manger.',
        difficulty: 'easy',
      },
      {
        question: 'Que dit-on après avoir mangé ?',
        choices: ['Bismillah', 'Alhamdulillah', 'Astaghfirullah', 'InshAllah'],
        correctIndex: 1,
        explanation: 'On dit "Alhamdulillah" (Louange à Allah) pour remercier Allah de la nourriture.',
        difficulty: 'easy',
      },
      {
        question: 'Que dit-on quand on éternue ?',
        choices: ['Bismillah', 'SubhanAllah', 'Alhamdulillah', 'MashAllah'],
        correctIndex: 2,
        explanation: 'Celui qui éternue dit "Alhamdulillah" et on lui répond "Yarhamukallah" (Qu\'Allah te fasse miséricorde).',
        difficulty: 'easy',
      },
      {
        question: 'Que signifie avoir de bonnes manières en Islam ?',
        choices: ['Être riche', 'Bien se comporter avec les autres', 'Parler fort', 'Voyager souvent'],
        correctIndex: 1,
        explanation: 'Avoir de bonnes manières signifie adopter un bon comportement, être respectueux, doux et juste avec les autres.',
        difficulty: 'easy',
      },
      {
        question: 'Sourire à son frère musulman est :',
        choices: ['Une perte de temps', 'Une faiblesse', 'Une aumône', 'Une obligation lourde'],
        correctIndex: 2,
        explanation: 'Sourire est considéré comme une aumône et fait partie des bonnes manières enseignées en Islam.',
        difficulty: 'easy',
      },
      {
        question: 'Dire la vérité fait partie :',
        choices: ['Des bonnes manières', 'Du commerce uniquement', 'Des habitudes culturelles', 'Des choses déconseillées'],
        correctIndex: 0,
        explanation: 'La véracité est une qualité essentielle et fait partie des nobles caractères encouragés en Islam.',
        difficulty: 'easy',
      },
      {
        question: 'Être respectueux envers ses parents est :',
        choices: ['Optionnel', 'Un mauvais signe', 'Une obligation importante', 'Réservé aux adultes seulement'],
        correctIndex: 2,
        explanation: 'Le respect et la bonté envers les parents sont des obligations majeures en Islam.',
        difficulty: 'easy',
      },
      {
        question: 'Rendre le salut (Salam) est :',
        choices: ['Interdit', 'Recommandé et obligatoire d’y répondre', 'Réservé aux savants', 'Une simple coutume'],
        correctIndex: 1,
        explanation: 'Donner le salam est recommandé et y répondre est obligatoire selon les règles islamiques.',
        difficulty: 'easy',
      },
      {
        question: 'Faire preuve de patience face à une offense est :',
        choices: ['Une faiblesse', 'Une mauvaise attitude', 'Une noble qualité', 'Interdit'],
        correctIndex: 2,
        explanation: 'La patience face aux torts fait partie des qualités nobles et des bonnes manières.',
        difficulty: 'easy',
      },
      {
        question: 'Se moquer des autres est :',
        choices: ['Permis', 'Une bonne plaisanterie', 'Interdit', 'Recommandé entre amis'],
        correctIndex: 2,
        explanation: 'Se moquer ou rabaisser les autres est interdit et contredit les bonnes manières.',
        difficulty: 'easy',
      },
      {
        question: 'Aider une personne dans le besoin est :',
        choices: ['Un mauvais calcul', 'Un acte méritoire', 'Une perte de temps', 'Interdit'],
        correctIndex: 1,
        explanation: 'Aider les autres est un acte méritoire et fait partie du bon comportement.',
        difficulty: 'easy',
      },
      {
        question: 'Respecter ses engagements est :',
        choices: ['Facultatif', 'Une qualité des croyants', 'Un détail sans importance', 'Réservé aux commerçants'],
        correctIndex: 1,
        explanation: 'Tenir ses promesses est une qualité essentielle et une preuve de bon caractère.',
        difficulty: 'easy',
      },
      {
        question: 'Parler avec douceur est :',
        choices: ['Un signe de faiblesse', 'Une bonne manière', 'Interdit en public', 'Réservé aux enfants'],
        correctIndex: 1,
        explanation: 'La douceur dans la parole fait partie des nobles caractères encouragés en Islam.',
        difficulty: 'easy',
      },
      {
    question: 'Comment doit-on manger selon les bonnes manières enseignées en Islam ?',
    choices: ['Avec la main gauche', 'En mentionnant le nom d’Allah et avec la main droite', 'Debout obligatoirement', 'En silence total sans invocation'],
    correctIndex: 1,
    explanation: 'Il est enseigné de dire "Bismillah" avant de manger et d’utiliser la main droite.',
    difficulty: 'easy',
  },
  {
    question: 'Être humble envers les autres est :',
    choices: ['Un défaut', 'Une qualité noble', 'Interdit', 'Réservé aux pauvres'],
    correctIndex: 1,
    explanation: 'L’humilité est une qualité aimée et fait partie des nobles caractères.',
    difficulty: 'easy',
  },
  {
    question: 'Couper la parole à quelqu’un sans raison est :',
    choices: ['Une bonne manière', 'Interdit ou blâmable', 'Recommandé', 'Un signe d’intelligence'],
    correctIndex: 1,
    explanation: 'Interrompre les autres sans raison est contraire au respect et aux bonnes manières.',
    difficulty: 'easy',
  },
  {
    question: 'Remercier quelqu’un qui nous a rendu service est :',
    choices: ['Inutile', 'Une bonne manière', 'Interdit', 'Un signe de faiblesse'],
    correctIndex: 1,
    explanation: 'Montrer de la reconnaissance fait partie des bonnes manières et renforce les liens entre les personnes.',
    difficulty: 'easy',
  },
  {
    question: 'La pudeur (haya) est :',
    choices: ['Un mauvais trait de caractère', 'Une branche de la foi', 'Un obstacle à la réussite', 'Réservée aux femmes uniquement'],
    correctIndex: 1,
    explanation: 'La pudeur est une qualité noble et fait partie de la foi.',
    difficulty: 'easy',
  },
  {
    question: 'Être généreux envers ses invités est :',
    choices: ['Une tradition sans importance', 'Un mauvais calcul financier', 'Une qualité recommandée', 'Interdit'],
    correctIndex: 2,
    explanation: 'Honorer et être généreux envers ses invités fait partie des bonnes manières.',
    difficulty: 'easy',
  },
  {
    question: 'Espionner ou chercher les défauts des autres est :',
    choices: ['Permis', 'Recommandé', 'Interdit', 'Une preuve de curiosité saine'],
    correctIndex: 2,
    explanation: 'Chercher les défauts des autres et les espionner est interdit et contraire au bon comportement.',
    difficulty: 'easy',
  },
  {
    question: 'Être juste même avec quelqu’un qu’on n’aime pas est :',
    choices: ['Optionnel', 'Une obligation morale', 'Impossible', 'Réservé aux juges'],
    correctIndex: 1,
    explanation: 'La justice est une obligation, même envers ceux avec qui on a un désaccord.',
    difficulty: 'easy',
  },
  {
    question: 'Saluer en premier est :',
    choices: ['Déconseillé', 'Un signe d’orgueil', 'Recommandé', 'Interdit'],
    correctIndex: 2,
    explanation: 'Commencer par le salut est recommandé et reflète un bon comportement.',
    difficulty: 'easy',
  }

      // === NORMAL ===
      {
        question: 'Avec quelle main doit-on manger selon la Sunna ?',
        choices: ['La main gauche', 'La main droite', 'Les deux mains', 'Cela n\'a pas d\'importance'],
        correctIndex: 1,
        explanation: 'Le Prophète (ﷺ) a dit : "Mangez avec votre main droite." La main droite est utilisée pour les actes nobles.',
        difficulty: 'normal',
      },
      {
        question: 'Que doit-on dire en entrant dans une maison ?',
        choices: ['Allahu Akbar', 'Astaghfirullah', 'Assalamou Alaykoum', 'SubhanAllah'],
        correctIndex: 2,
        explanation: 'On donne le Salam (Assalamou Alaykoum) en entrant dans une maison, même si elle est vide.',
        difficulty: 'normal',
      },
      {
        question: 'Quelle est la Sunna avant de dormir ?',
        choices: ['Manger un repas léger', 'Réciter Ayat al-Kursi', 'Faire du sport', 'Prendre un bain'],
        correctIndex: 1,
        explanation: 'Le Prophète (ﷺ) récitait Ayat al-Kursi et les 3 dernières sourates avant de dormir pour être protégé.',
        difficulty: 'normal',
      },
      {
        question: 'Que dit-on quand quelqu\'un nous fait du bien ?',
        choices: ['SubhanAllah', 'InshAllah', 'JazakAllahu Khayran', 'Astaghfirullah'],
        correctIndex: 2,
        explanation: '"JazakAllahu Khayran" signifie "Qu\'Allah te récompense par le bien". C\'est la meilleure façon de remercier quelqu\'un.',
        difficulty: 'normal',
      },
      // === HARD ===
      {
        question: 'Que dit-on quand on voit quelque chose de beau ou d\'admirable ?',
        choices: ['Bismillah', 'InshAllah', 'MashAllah', 'Astaghfirullah'],
        correctIndex: 2,
        explanation: '"MashAllah" (Ce qu\'Allah a voulu) protège du mauvais œil. On le dit pour admirer ce qu\'Allah a créé ou accordé.',
        difficulty: 'hard',
      },
      {
        question: 'Quelle invocation le Prophète (ﷺ) recommandait-il en sortant de la maison ?',
        choices: ['Bismillah, tawakkaltu ala Allah', 'SubhanAllah wal hamdulillah', 'Astaghfirullah al-Azim', 'La hawla wa la quwwata illa billah'],
        correctIndex: 0,
        explanation: '"Bismillah, tawakkaltu ala Allah" (Au nom d\'Allah, je place ma confiance en Allah). Le Prophète (ﷺ) ajoutait : "il n\'y a de force et de puissance qu\'en Allah".',
        difficulty: 'hard',
      },
      {
        question: 'Selon la Sunna, avec quel pied entre-t-on dans la mosquée ?',
        choices: ['Le pied gauche', 'Le pied droit', 'Les deux pieds en même temps', 'Cela n\'a pas d\'importance'],
        correctIndex: 1,
        explanation: 'On entre dans la mosquée avec le pied droit et on en sort avec le pied gauche. Le droit est associé au bien dans la Sunna.',
        difficulty: 'hard',
      },
      {
        question: 'Que doit-on dire quand on voit quelqu\'un éprouver un malheur ?',
        choices: ['Alhamdulillah alladhi afani', 'SubhanAllah', 'MashAllah', 'InshAllah ça ira mieux'],
        correctIndex: 0,
        explanation: 'On dit discrètement "Alhamdulillah alladhi afani" (Louange à Allah qui m\'a préservé de cette épreuve et m\'a favorisé).',
        difficulty: 'hard',
      },
      {
        question: 'Combien de droits du voisin l\'Islam reconnaît-il selon le hadith ?',
        choices: ['3 droits', '7 droits', '10 droits', 'Plus de 30 droits'],
        correctIndex: 3,
        explanation: 'Le Prophète (ﷺ) a dit que Jibril lui a tellement recommandé le voisin qu\'il a cru qu\'il allait en faire un héritier. L\'Islam reconnaît de nombreux droits du voisin.',
        difficulty: 'hard',
      },
    ],
  },
];

/** Number of questions per quiz session */
export const QUESTIONS_PER_QUIZ = 10;
